### ISSUE TITLE
when runing the data preparation step, the data can not be obtained

### ISSUE THREAD

**Issue by PengpengGuan** [yyoshiaki/sclinker-skg#1]
Thank you for providing the detailed installation and runing steps. But when runing this command "bash scripts/prep_data.sh ${PWD}", I find several file can not be obtained.

https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/DeepLearning/Dey_DeepBoost_Imperio/data_extra/AllPredictions.AvgHiC.ABC0.015.minus150.withcolnames.ForABCPaper.txt.gz

wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/1000G_Phase3_baselineLD_v2.1_ldscores.tgz
tar xvf 1000G_Phase3_baselineLD_v2.1_ldscores.tgz

wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/1000G_Phase3_frq.tgz
tar xvf 1000G_Phase3_frq.tgz 

wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/1000G_Phase3_weights_hm3_no_MHC.tgz
tar xvf 1000G_Phase3_weights_hm3_no_MHC.tgz

wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/1000G_Phase3_plinkfiles.tgz
tar xvf 1000G_Phase3_plinkfiles.tgz

# wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/hapmap3_snps.tgz
# tar xvf hapmap3_snps.tgz

# https://github.com/bulik/ldsc/wiki/Partitioned-Heritability-from-Continuous-Annotations
wget https://data.broadinstitute.org/alkesgroup/LDSCORE/w_hm3.snplist.bz2

https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/Jagadeesh_Dey_sclinker/scdata/pbmc-processed-annotated.h5ad

Can you provide these files again so that we can better use this tool? Thanks a lot

**Comment by yyoshiaki** [comment]
Hi,
Because these codes are based on sclinker and their original files, could you look for the original repositories?
They may have modified some locations.
 
https://www.nature.com/articles/s41588-022-01187-9
https://github.com/karthikj89/scgenetics

For example, The ABC file should be accessible using gutils.
https://github.com/kkdey/GSSG/tree/master?tab=readme-ov-file#step-2-gene-setprogram-to-snp-annotation

**Comment by PengpengGuan** [comment]
> Hi, Because these codes are based on sclinker and their original files, could you look for the original repositories? They may have modified some locations.
> 
> https://www.nature.com/articles/s41588-022-01187-9 https://github.com/karthikj89/scgenetics
> 
> For example, The ABC file should be accessible using gutils. https://github.com/kkdey/GSSG/tree/master?tab=readme-ov-file#step-2-gene-setprogram-to-snp-annotation

Thank you so much.

I have got  the links of these file.

wget https://storage.googleapis.com/broad-alkesgroup-public/LDSCORE/Jagadeesh_Dey_sclinker/extras/AllPredictions.AvgHiC.ABC0.015.minus150.withcolnames.ForABCPaper.txt.gz
wget https://dazaxieshare.vip.cpolar.cn/09.LDSC/reference/1000G_Phase3_baselineLD_v2.2_ldscores.tgz
wget https://dazaxieshare.vip.cpolar.cn/09.LDSC/reference/1000G_Phase3_frq.tgz
wget https://dazaxieshare.vip.cpolar.cn/09.LDSC/reference/1000G_Phase3_weights_hm3_no_MHC.tgz
wget https://dazaxieshare.vip.cpolar.cn/09.LDSC/reference/w_hm3.snplist.bz2

thank you again.
